"""Generate 16x16 placeholder pixel art for the sunlitweed KubeJS add-on (stdlib only)."""
import struct
import sys
import zlib
from pathlib import Path

OUT = Path(sys.argv[1])

PALETTE = {
    ".": (0, 0, 0, 0),
    "G": (38, 92, 34, 255),     # dark leaf
    "g": (66, 145, 50, 255),    # leaf / bud
    "l": (120, 196, 78, 255),   # light bud
    "w": (222, 234, 204, 255),  # trichome frost
    "o": (214, 124, 44, 255),   # orange pistil
    "b": (104, 82, 46, 255),    # stalk
    "B": (68, 50, 30, 255),     # cut stalk end
    "S": (82, 66, 40, 255),     # seed outline
    "s": (138, 112, 68, 255),   # seed body
    "p": (238, 234, 220, 255),  # paper
    "P": (196, 190, 174, 255),  # paper shade
    "k": (176, 128, 80, 255),   # tan / filter
    "t": (124, 78, 46, 255),    # tubabacco wrap
    "T": (84, 50, 30, 255),     # wrap shade
    "r": (236, 86, 34, 255),    # ember
    "a": (160, 160, 160, 255),  # ash
}

# Dried versions: same sprites, muted olive/tan palette
DRIED = {"G": "Y", "g": "y", "l": "z"}
PALETTE.update({
    "Y": (92, 96, 48, 255),
    "y": (138, 136, 70, 255),
    "z": (176, 168, 102, 255),
})

SPRITES = {
    "item/weed_seed": """
................
................
................
................
.....SS.........
....SssS........
....SssS..SS....
.....SS..SssS...
.........SssS...
...SS.....SS....
..SssS..........
..SssS....SS....
...SS....SssS...
.........SssS...
..........SS....
................
""",
    "item/weed_stalk": """
...........gl...
..........glwl..
.....G...gglog..
....GgG..gwlgl..
...GgggG.glog...
....GgG.b.gg....
.G...G.b........
GgG...b..gwl....
.GgG.b..glogl...
..Gb...gwlgl....
...b.G..glg.....
..b.GgG.........
.b...GgG........
b.....G.........
B...............
................
""",
    "item/weed_bud": """
................
......gl........
.....glwg.......
....glolgl......
...gwlgwolg.....
...glogllwg.....
..glwlgolglg....
..gollwgllog....
...glgolwlg.....
...gwllglog.....
....glogwg......
.....glgl.......
......bg........
......b.........
................
................
""",
    "item/ground_weed": """
................
................
................
................
................
................
................
......g.l.......
....lgGlgo......
...gGlgwlgl.....
..glogGlgolg....
.gGlwglGlwgGl...
.glgGolglgGlog..
..GgGgGgGgGgG...
................
................
""",
    "item/blunt_wrap": """
................
................
................
...kkkkkkkkk....
..kttttttttTk...
..kttTtttttTk...
..ktttttTttTk...
..ktTttttttTk...
..kttttTtttTk...
..kttttttTtTk...
..ktttTttttTk...
..kTTTTTTTTTk...
...kkkkkkkkk....
................
................
................
""",
    "item/joint": """
..............a.
.............ra.
............rpP.
...........ppP..
..........ppP...
.........ppP....
........ppP.....
.......ppP......
......ppP.......
.....ppP........
....ppP.........
...ppP..........
..pP............
.kP.............
.k..............
................
""",
    "item/blunt": """
..............a.
.............ra.
............rrt.
...........tttT.
..........tttT..
.........tttT...
........tttT....
.......tttT.....
......tttT......
.....tttT.......
....tttT........
...tttT.........
..tttT..........
.TttT...........
.TTT............
................
""",
    "block/weed_stage0": """
................
................
................
................
................
................
................
................
................
................
................
................
..g.g.....g..g..
...g.......gg...
...b........b...
...b........b...
""",
    "block/weed_stage1": """
................
................
................
................
................
................
................
................
......G.G.......
.....GgGgG......
..G...GbG...G...
.GgG...b...GgG..
..GgG..b..GgG...
....G.Gb.G......
.......b........
.......b........
""",
    "block/weed_stage2": """
................
................
................
................
.......g........
......ggg.......
.G...G.b.G...G..
.GgG.GgbgG.GgG..
..GgG..b..GgG...
....GG.b.GG.....
.G.....b.....G..
GgGG...b...GGgG.
.GgGG.Gb.GGgG...
...GGGgbgGG.....
.......b........
.......b........
""",
    "block/weed_stage3": """
.......l........
......lwl.......
......lol.......
.l...GgbgG...l..
lwl.GgGbGgG.lwl.
lol...Gb.G..lol.
.G.G...b...G.G..
.GgG.lwbl..GgG..
..GgGlobl.GgG...
....GG.b.GG.....
.lw....b....wl..
GolGG..b..GGloG.
.GgGG.Gb.GGgG...
...GGGgbgGG.....
.......b........
.......b........
""",
}
# Dried stalk is the fresh stalk recoloured
SPRITES["item/dried_weed_stalk"] = "".join(DRIED.get(c, c) for c in SPRITES["item/weed_stalk"])


def write_png(path, rows):
    raw = b"".join(b"\x00" + b"".join(bytes(PALETTE[c]) for c in row) for row in rows)
    def chunk(tag, data):
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    png = (b"\x89PNG\r\n\x1a\n"
           + chunk(b"IHDR", struct.pack(">IIBBBBB", 16, 16, 8, 6, 0, 0, 0))
           + chunk(b"IDAT", zlib.compress(raw, 9))
           + chunk(b"IEND", b""))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(png)


for name, art in SPRITES.items():
    rows = art.strip("\n").split("\n")
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), f"{name}: bad grid size"
    write_png(OUT / f"{name}.png", rows)
    print("wrote", name)
